/*
 * config.h
 *
 *  Created on: 2015?12?18?
 *      Author: Administrator
 */

#ifndef APP_INCLUDE_CONFIG_H_
#define APP_INCLUDE_CONFIG_H_

#define HARDWARE_VERSOIN_NUM	(0x01)
#define INDUSTR_VERSOIN_NUM		(0x01)
#define MAIN_SOFTWARE_VERSOIN_NUM	(0x01)
#define SOFTWARE_VERSOIN_NUM		(0x01)
#define DEVICE_VERSOIN ((HARDWARE_VERSOIN_NUM<<24)|(INDUSTR_VERSOIN_NUM<<16)|(MAIN_SOFTWARE_VERSOIN_NUM<<8)|SOFTWARE_VERSOIN_NUM)

#define DATE_YEAR		2017
#define DATE_MONTH		3
#define DATE_DAY		14

#define ENCRYPTION		1

#if defined STM32F10X_LD
#define ENCRYPT_FLASH_ADDRESS 0x8008000
#elif defined STM32F10X_MD
#define ENCRYPT_FLASH_ADDRESS 0x8008000
#elif defined STM32F10X_HD
#define ENCRYPT_FLASH_ADDRESS 0x8008000
#elif defined STM32F10X_CL
#define ENCRYPT_FLASH_ADDRESS 0x8008000
#endif

#define PAGE_SIZE		1024


#define HEART_INTERVAL	(1000/OS_TICKS_PER_SEC)



#define PLUSE_IN_WIDTH_MIN	(10/HEART_INTERVAL)
#define PLUSE_IN_WIDTH_MAX	(1000/HEART_INTERVAL)
#define PLUSE_IN_SPACE_MIN	(10/HEART_INTERVAL)
#define PLUSE_IN_SPACE_DEF	(100/HEART_INTERVAL)
#define PLUSE_IN_SPACE_MAX	(2500/HEART_INTERVAL)



#define EE_TYPE	255








#endif /* APP_INCLUDE_CONFIG_H_ */
